## Homework #3

It is advisable to do all tasks manually, then check the results using numpy.

__1.__ Identify which products of matrices $AB$ and $BA$ are defined and find the dimensions of the matrices obtained:

   a) $A$ — matrix $4\times 2$, $B$ — matrix $4\times 2$;
    
   b) $A$ — matrix $2\times 5$, $B$ — matrix $5\times 3$;
    
   c) $A$ — matrix $8\times 3$, $B$ — matrix $3\times 8$;
    
   d) $A$ — square matrix $4\times 4$, $B$ — square matrix $4\times 4$.


a) It cannot be multiplied
b) AB 2X3
c) AB 8X8, BA 3X3
d) АВ BA 4X4

__2.__ Find the sum and product of the matrices $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ and $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


### $$A+B
=
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} 
+
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=$$

### $$=
\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}
= 
\begin{pmatrix}
5 & -3\\ 
3 &  5
\end{pmatrix}$$

### $$AB
=
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
\cdot 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
=$$ 
### $$=\begin{pmatrix}
1\cdot 4 + -2\cdot 0 & 1\cdot (-1) -2\cdot 5 \\ 
3\cdot 4 + 0\cdot 0 & 3\cdot (-1) + 0\cdot 5
\end{pmatrix} 
=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$

### $$BA
= 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
\cdot  
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
=$$
### $$=
\begin{pmatrix}
4\cdot 1 + -1\cdot 3 & 4\cdot (-2) + -1\cdot 0 \\ 
0\cdot 1 + 5\cdot 3 & 0\cdot (-2) + 5\cdot 0
\end{pmatrix}
= 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Matrix A\n{A}')
print(f'Matrix B\n{B}')
print(f'Matrix С = A + B\n{A + B}')
print(f'Matrix AB\n{np.dot(A, B)}')
print(f'Matrix BА\n{np.dot(B, A)}')

Matrix A
[[ 1 -2]
 [ 3  0]]
Matrix B
[[ 4 -1]
 [ 0  5]]
Matrix С = A + B
[[ 5 -3]
 [ 3  5]]
Matrix AB
[[  4 -11]
 [ 12  -3]]
Matrix BА
[[ 1 -8]
 [15  0]]


__3.__ From the patterns of addition and multiplication of matrices by a number, we can conclude that matrices of the same size form a linear space. Calculate the linear combination $3A-2B+4C$ for matrices $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### $$3A-2B+4C=$$

### $$\begin{pmatrix}
3 & 21\\ 
9 & -18\\
\end{pmatrix}
+
\begin{pmatrix}
0 & -10\\ 
-4 & 2\\
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\ 
4 & 4\\
\end{pmatrix}
=$$
### $$
=
\begin{pmatrix}
3+0+8 & 21-10-16\\ 
9-4+4 & -18+2+4\\
\end{pmatrix}
=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Matrix 3𝐴−2𝐵+4𝐶\n{3*A - 2*B + 4*C}')

Matrix 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Given matrix $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Calculate $AA^{T}$ и $A^{T}A$.

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Matrix:\n{A}')
print(f'Transposed matrix:\n{A.T}')
print(f'Matrix 𝐴*𝐴𝑇\n{np.dot(A,A.T)}')
print(f'Matrix 𝐴𝑇*𝐴\n{np.dot(A.T,A)}')

Matrix:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Transposed matrix:
[[ 4  5  2]
 [ 1 -2  3]]
Matrix 𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Matrix 𝐴𝑇*𝐴
[[45  0]
 [ 0 14]]


__5*.__ Write a function in Python to multiply two arbitrary matrices without using NumPy.

In [4]:

def skalar_prod(v1, v2):
    return sum([i*j for i,j in zip(v1,v2)])
       

def matrix_product(A, B, display_result=True):
    result = []
    try:
        for row_a in A:
            internal_row = []
            for k in range(len(B[0])):
                column = [B[i][k] for i in range(len(B))]
                internal_row.append(skalar_prod(row_a, column))
            result.append(internal_row)
        if display_result:
            for row in result:
                print(row)
        return result
    except Exception as e:
        print('wrong dimensions!')
        print(e)

In [5]:
# Check

a = [[1,2,3],
     [5,3,7]]
b = [[1,1],
     [2,2],
     [3,3]]
с = matrix_product(a,b)

[14, 14]
[32, 32]


In [6]:
# Comparing with NUMPY

import numpy as np
a_np = np.array(a)
b_np = np.array(b)
a_np.dot(b_np)

array([[14, 14],
       [32, 32]])