## Homework #5

In [2]:
# Important libraries

import numpy as np
np.set_printoptions(precision = 2, suppress = True)

### Singular matrix decomposition

1. Find with NumPy the SVD for the matrix

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [3]:
# Solution

A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype = float)
D[np.diag_indices(min(A.shape))] = s

print(f'Matrix D:\n{D}')
print(f'Matrix U:\n{U}')
print(f'Matrix V:\n{V}')

print(np.dot(np.dot(U, D), V.T))

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. For the matrix from the previous task find:

    a) Euclidean norm;
    
    b) Frobenius norm.

In [4]:
# a

print(max(s))

# b

print(np.linalg.norm(s))

8.824868854820442
11.045361017187261
